version: "3.7"
services:
  moongate_database_mongo:
    build: "./moongate_database_mongo"
    image: cepheus990910/moongate_database_mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: honeypot_user
      MONGO_INITDB_ROOT_PASSWORD: This_Is_N0t_@_Str0ng_En0ugh_P@ssw0rd
      MONGO_INITDB_DATABASE: admin
    volumes:
      - mongo_data:/data/db
    networks:
      MOONGATE:
        aliases:
          - database-mongo

  moongate_service:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    environment:
      - API_URL=value
      - BRAND_NAME=Networked
    image: cepheus990910/moongate_service:${MOONGATE_VERSION_TAG}
    depends_on:
      - moongate_database_mongo
    networks:
      MOONGATE:
        aliases:
          - moongate-service
volumes:
  mongo_data: null
networks:
  MOONGATE: null
